source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'WebRTC-Demo' do
    pod 'GoogleWebRTC', '~> 1.1'
    pod 'Promises'
    pod 'Anchorage'
    pod 'SwiftPhoenixClient'
    pod 'Texture/Core'
end
